# Generated by Django 2.2.3 on 2019-07-14 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.IntegerField(max_length=20)),
                ('casename', models.CharField(max_length=20)),
                ('casedate', models.DateField()),
                ('casedesc', models.TextField(max_length=200)),
                ('casemanager', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseid', models.IntegerField(max_length=20)),
                ('taskname', models.CharField(max_length=20)),
                ('taskdate', models.DateField()),
                ('taskdesc', models.TextField(max_length=200)),
                ('taskmanager', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
